Repository InhaBas/Inhabas.com-api, pull requests merged in 2024-01, with the labels that each got.

#206 [feature/#204] [동아리 소개] API 구현
  .github/workflows/gradle-build.yml
  resource-server/src/main/java/com/inhabas/api/config/SwaggerConfig.java
  resource-server/src/main/java/com/inhabas/api/config/WebSecurityConfig.java
  resource-server/src/main/java/com/inhabas/api/domain/board/domain/NormalBoard.java
  resource-server/src/main/java/com/inhabas/api/domain/board/domain/valueObject/Content.java
  resource-server/src/main/java/com/inhabas/api/domain/board/domain/valueObject/Title.java
  resource-server/src/main/java/com/inhabas/api/domain/board/repository/NormalBoardRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/club/domain/entity/ClubHistory.java
  resource-server/src/main/java/com/inhabas/api/domain/club/dto/ClubHistoryDto.java
  resource-server/src/main/java/com/inhabas/api/domain/club/dto/SaveClubHistoryDto.java
  resource-server/src/main/java/com/inhabas/api/domain/club/repository/ClubHistoryRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubHistoryService.java
  resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubHistoryServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/comment/domain/valueObject/Contents.java
  resource-server/src/main/java/com/inhabas/api/domain/contest/domain/ContestBoard.java
  resource-server/src/main/java/com/inhabas/api/domain/contest/repository/ContestBoardRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/signUp/exception/NotWriteAnswersException.java
  resource-server/src/main/java/com/inhabas/api/domain/signUp/exception/NotWriteProfileException.java
  resource-server/src/main/java/com/inhabas/api/domain/signUp/usecase/SignUpServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/signUpSchedule/domain/entity/SignUpSchedule.java
  resource-server/src/main/java/com/inhabas/api/domain/signUpSchedule/exception/InvalidDateException.java
  resource-server/src/main/java/com/inhabas/api/domain/signUpSchedule/exception/SignUpNotAvailableException.java
  resource-server/src/main/java/com/inhabas/api/web/ClubHistoryController.java
  resource-server/src/main/java/com/inhabas/api/web/ExceptionController.java
  resource-server/src/main/java/com/inhabas/api/web/interceptor/SignUpControllerInterceptor.java
  resource-server/src/test/java/com/inhabas/api/domain/BaseEntityTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/domain/valueObject/BoardContentTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/domain/valueObject/BoardContentsTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/domain/valueObject/TitleTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/dto/SaveBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/dto/UpdateBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/repository/NormalBoardRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/board/usecase/BoardServiceTest.java
  resource-server/src/test/java/com/inhabas/api/domain/club/domain/entity/ClubHistoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/club/dto/ClubHistoryDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/club/dto/SaveClubHistoryDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/club/usecase/ClubHistoryServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/domain/comment/domain/valueObject/CommentContentTest.java
  resource-server/src/test/java/com/inhabas/api/domain/comment/repository/CommentRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/contestBoard/dto/SaveContestBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/contestBoard/dto/UpdateContestBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/contestBoard/repository/ContestBoardRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/contestBoard/usecase/ContestBoardServiceTest.java
  resource-server/src/test/java/com/inhabas/api/domain/signUp/usecase/SignUpServiceTest.java
  resource-server/src/test/java/com/inhabas/api/domain/signUpSchedule/domain/entity/SignUpScheduleTest.java
  resource-server/src/test/java/com/inhabas/api/web/BoardControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/ClubHistoryControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/CommentControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/ContestBoardControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/SignUpScheduleControllerTest.java
Labels: new feature

#210 [feature/#209] 정책 관련 API 구현
  resource-server/src/main/java/com/inhabas/api/config/WebSecurityConfig.java
  resource-server/src/main/java/com/inhabas/api/domain/BaseEntity.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/domain/PolicyTerm.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/domain/PolicyType.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/dto/PolicyTermDto.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/dto/SavePolicyTernDto.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/respository/PolicyTermRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/usecase/PolicyTermService.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/usecase/PolicyTermServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/web/PolicyTermController.java
  resource-server/src/test/java/com/inhabas/api/domain/club/usecase/ClubHistoryServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/domain/PolicyTermTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/domain/PolicyTypeTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/dto/PolicyTermDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/dto/SavePolicyTernDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/usecase/PolicyTermServiceTest.java
  resource-server/src/test/java/com/inhabas/api/web/PolicyTermControllerTest.java
Labels: new feature

#214 [feature/#167] Readme.md작성
  COMMITER-INSTRUCTION.md
  CONTRIBUTING.md
  README.md
  STYLE-CONVENTION.md
  docs/back-end/back-end.md
  docs/back-end/ibas_eclipse_formatting.xml
  docs/back-end/ibas_intellij_formatting.xml
  docs/fornt-end/front-end.md
  docs/images/commiter-instruction01-select-merge-commit.png
  docs/images/commitor-instruction02-select-merge-pull-request.png
  docs/images/commitor-instruction03-modify-title-body.png
  docs/images/logo_purple.png
Labels: documentation, new feature

#216 [feature/#215] SpotlessApply적용
  build.gradle
Labels: new feature

#220 [Refactor/InhaBas#167] 리드미 수정 - 구글 컨벤션 반영
  CONTRIBUTING.md
  STYLE-CONVENTION.md
  docs/back-end/ibas_eclipse_formatting.xml
  docs/back-end/ibas_intellij_formatting.xml
Labels: refactor
