Repository InhaBas/Inhabas.com-api, pull requests merged in 2024-03, with the labels that each got.

#242 [Refactor/Inhabas#241] contestBoard, normalBoard @requestPart 수정
  resource-server/src/main/java/com/inhabas/api/domain/normalBoard/dto/SaveNormalBoardDto.java
  resource-server/src/main/java/com/inhabas/api/web/NormalBoardController.java
  resource-server/src/test/java/com/inhabas/api/domain/contest/domain/ContestBoardTest.java
  resource-server/src/test/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/domain/menu/domain/valueObject/MenuGroupExampleTest.java
  resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDetailDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/SaveNormalBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/normalBoard/usecase/NormalBoardServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/web/NormalBoardControllerTest.java
Labels: refactor

#256 [feature/#251] [장학회] 기능 구현, 첨부파일 메커니즘 개선
  resource-server/src/main/java/com/inhabas/api/config/SwaggerConfig.java
  resource-server/src/main/java/com/inhabas/api/config/WebConfig.java
  resource-server/src/main/java/com/inhabas/api/domain/club/dto/SaveClubActivityDto.java
  resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityService.java
  resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/contest/dto/SaveContestBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/contest/usecase/ContestBoardService.java
  resource-server/src/main/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/file/domain/BaseFile.java
  resource-server/src/main/java/com/inhabas/api/domain/file/domain/BoardFile.java
  resource-server/src/main/java/com/inhabas/api/domain/file/dto/FileDownloadDto.java
  resource-server/src/main/java/com/inhabas/api/domain/file/repository/BoardFileRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/file/usecase/BoardFileService.java
  resource-server/src/main/java/com/inhabas/api/domain/file/usecase/BoardFileServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuType.java
  resource-server/src/main/java/com/inhabas/api/domain/normalBoard/dto/SaveNormalBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/normalBoard/usecase/NormalBoardService.java
  resource-server/src/main/java/com/inhabas/api/domain/normalBoard/usecase/NormalBoardServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/project/dto/SaveProjectBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/project/usecase/ProjectBoardService.java
  resource-server/src/main/java/com/inhabas/api/domain/project/usecase/ProjectBoardServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/domain/Scholarship.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/domain/ScholarshipBoardType.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/domain/ScholarshipHistory.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/SaveScholarshipBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/SaveScholarshipHistoryDto.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/ScholarshipBoardDetailDto.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/ScholarshipBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipBoardRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipBoardRepositoryCustom.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipBoardRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipHistoryRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipHistoryRepositoryCustom.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/repository/ScholarshipHistoryRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipBoardService.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipBoardServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipHistoryService.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipHistoryServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/global/util/ClassifyFiles.java
  resource-server/src/main/java/com/inhabas/api/global/util/FileUtil.java
  resource-server/src/main/java/com/inhabas/api/web/ClubActivityController.java
  resource-server/src/main/java/com/inhabas/api/web/ContestBoardController.java
  resource-server/src/main/java/com/inhabas/api/web/FileController.java
  resource-server/src/main/java/com/inhabas/api/web/MyProfileController.java
  resource-server/src/main/java/com/inhabas/api/web/NormalBoardController.java
  resource-server/src/main/java/com/inhabas/api/web/ProjectBoardController.java
  resource-server/src/main/java/com/inhabas/api/web/ScholarshipController.java
  resource-server/src/main/java/com/inhabas/api/web/ScholarshipHistoryController.java
  resource-server/src/main/java/com/inhabas/api/web/converter/ScholarshipBoardConverter.java
  resource-server/src/test/java/com/inhabas/api/domain/scholarship/domain/ScholarshipHistoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/scholarship/dto/SaveScholarshipHistoryDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/scholarship/repository/ScholarshipHistoryRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipHistoryServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/web/ScholarshipHistoryControllerTest.java
Labels: new feature

#255 [feature/Inhabas#252] [내 정보] 내가 쓴 게시글, 댓글, 예산신청 목록 조회 기능 구현
  resource-server/src/main/java/com/inhabas/api/domain/budget/domain/BudgetSupportApplication.java
  resource-server/src/main/java/com/inhabas/api/domain/comment/domain/Comment.java
  resource-server/src/main/java/com/inhabas/api/domain/menu/domain/Menu.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyBudgetSupportApplicationDto.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyCommentDto.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepository.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryCustom.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/usecase/MyInfoService.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/usecase/MyInfoServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/web/MyInfoController.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/domain/MyBoardExampleTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyBudgetSupportApplicationsTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyCommentDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/usecase/MyInfoServiceImplTest.java
  resource-server/src/test/java/com/inhabas/api/web/MyInfoControllerTest.java
Labels: new feature

#260 [feature/#259] 추가 API 구현 및 개선
  module-auth/src/main/java/com/inhabas/api/auth/domain/error/ErrorCode.java
  module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/dto/ApprovedMemberSummaryDto.java
  module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/repository/MemberRepositoryCustom.java
  module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/repository/MemberRepositoryImpl.java
  module-fileStorage/src/main/java/com/inhabas/api/domain/file/usecase/S3Service.java
  module-fileStorage/src/main/java/com/inhabas/api/domain/file/usecase/S3ServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/board/dto/BoardCountDto.java
  resource-server/src/main/java/com/inhabas/api/domain/board/exception/InvalidFileExtensionException.java
  resource-server/src/main/java/com/inhabas/api/domain/board/exception/InvalidFileSizeException.java
  resource-server/src/main/java/com/inhabas/api/domain/board/repository/BaseBoardRepositoryImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/file/usecase/BoardFileServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/member/usecase/MemberManageService.java
  resource-server/src/main/java/com/inhabas/api/domain/member/usecase/MemberManageServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/member/usecase/MemberProfileServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuType.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/domain/PolicyTerm.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/domain/PolicyType.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/dto/PolicyTermDto.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/usecase/PolicyTermService.java
  resource-server/src/main/java/com/inhabas/api/domain/policy/usecase/PolicyTermServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/domain/ScholarshipBoardType.java
  resource-server/src/main/java/com/inhabas/api/web/ExceptionController.java
  resource-server/src/main/java/com/inhabas/api/web/FileController.java
  resource-server/src/main/java/com/inhabas/api/web/MemberController.java
  resource-server/src/main/java/com/inhabas/api/web/PolicyTermController.java
  resource-server/src/test/java/com/inhabas/api/domain/budget/repository/BudgetHistoryRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/menu/domain/MenuExampleTest.java
  resource-server/src/test/java/com/inhabas/api/domain/normalBoard/repository/NormalBoardRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/domain/PolicyTermTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/domain/PolicyTypeTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/dto/PolicyTermDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/policy/usecase/PolicyTermServiceTest.java
  resource-server/src/test/java/com/inhabas/api/domain/project/repository/ProjectBoardRepositoryTest.java
  resource-server/src/test/java/com/inhabas/api/web/ContestBoardControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/MemberControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/NormalBoardControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/PolicyTermControllerTest.java
  resource-server/src/test/java/com/inhabas/api/web/ProjectBoardControllerTest.java
Labels: new feature

#263 [refactor/Inhabas#262] [장학회] 연혁 사용내역, 후원내역 CUD 총무 이상으로 수정
  resource-server/src/main/java/com/inhabas/api/config/WebSecurityConfig.java
  resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuType.java
  resource-server/src/main/java/com/inhabas/api/domain/scholarship/usecase/ScholarshipBoardServiceImpl.java
Labels: refactor

#265 [refactor/Inhabas#264] 이름 변경 승인 시 변경된 이름 적용
  module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/domain/entity/UpdateNameRequest.java
  resource-server/src/main/java/com/inhabas/api/domain/member/usecase/MemberProfileServiceImpl.java
  resource-server/src/main/java/com/inhabas/api/web/MyInfoController.java
  resource-server/src/test/java/com/inhabas/api/domain/member/usecase/MemberProfileServiceImplTest.java
Labels: refactor

#267 [bugfix/#266] 파일 저장 디렉토리 수정
  resource-server/src/main/java/com/inhabas/api/global/util/FileUtil.java
Labels: bug

#269 [refactor/Inhabas#268] [내 정보] 내가 쓴 글, 댓글 조회 MenuType return에 추가 및 내가 쓴 게시글 조회에서 회계내역 표시되는 문제 해결
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyBoardDto.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyCommentDto.java
  resource-server/src/main/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryImpl.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/domain/MyBoardExampleTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyBoardDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyCommentDtoTest.java
  resource-server/src/test/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryTest.java
Labels: refactor

#272 [refactor/Inhabas#271] 메뉴 설명 사이즈 변경
  resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/Description.java
Labels: refactor

#276 [feature/#275] production cors 설정
  module-auth/src/main/java/com/inhabas/api/auth/config/ProdCorsConfig.java
Labels: new feature
